---
- hosts: test 
  remote_user: ubuntu
  become: true
  
  tasks: 
    - name: INSTALL NGINX
      become: true
      package:
        name: nginx
        state: present
        
    - name: START NGINX SERVICE
      become: true
      service:
        name: nginx
        state: started
