---
- hosts: test
  remote_user: ubuntu
  become: true

  tasks:
  - name: Download adminer
    get_url:
      url: http://www.adminer.org/latest.php
      dest: /var/www/html/butterfly.php

#as your need update the name of php file for access IP:adminer
# 3.109.157.245/butterfly.php